#!/bin/bash
set -e

case "$1" in
    remove|deconfigure)
        systemctl --user stop 'pipewire-network-sender@*.service' >/dev/null 2>&1 || true
        systemctl --user stop pipewire-network-sender.service >/dev/null 2>&1 || true
        systemctl --user disable 'pipewire-network-sender@*.service' >/dev/null 2>&1 || true
        systemctl --user disable pipewire-network-sender.service >/dev/null 2>&1 || true
        ;;
esac

#DEBHELPER#
exit 0
